### ISSUE TITLE
Nuevo sitio

### ISSUE THREAD

**Issue by xavier506** [LatamLink/latamlink.io#105]
Rediseño completo del sitio de LatamLink

Proceso:
- [x] Redacción de contenidos #114
- [ ] Wireframes del sitio / UX #115
- [ ] Revisión diseño del sitio / UI #116
- [ ] Desarrollo del sitio

Features:
- [ ] Directorio #102
